### ISSUE TITLE
PRD: Repair Console, Power Console, and Shape-Matching Repair System

### ISSUE THREAD

**Issue by jkeywo** [jkeywo/project-phoenix-v2#118]
## Problem Statement

The current Engineering console conflates two distinct responsibilities — power distribution and damage repair — into a single role, which limits crew scaling and reduces gameplay depth. The repair mechanic is passive: Engineering silently identifies which console is broken, then tells that console's operator to press a repair button. There is no skill check, no deception, and no social pressure. The power system exists only as a design document with no implementation.

Players need a repair experience that creates active communication between crew members, rewards correct identification under pressure, and punishes hasty guessing. They also need a power management system that lets a dedicated officer make meaningful trade-off decisions affecting the whole ship.

## Solution

Split Engineering into two separate consoles: **Repair** and **Power**.

The Repair console introduces a shape-matching mechanic: when a console breaks down, a damage icon (Square, Triangle, or Circle) appears on that console's screen. A second console simultaneously shows a decoy icon of a random shape. The Repair officer does not know which console is real and which is decoy — they must listen to their crew. The Repair officer has three repair teams and three shape buttons; pressing the correct shape dispatches a free team to fix the breakdown. A wrong press puts a team on cooldown. Teams are a finite resource managed via colour-coded progress bars.

The Power console implements the drafted power distribution design: 6 base points distributed across Helm, Weapons, and Science (1–4 each), an auxiliary battery providing up to 2 extra points, and a rate table governing battery charge/discharge. Power levels feed into the Modifier System (#117) to boost or penalise each console's performance.

## User Stories

1. As a **Repair officer**, I want to see the current breakdown at the head of the queue so I know which console needs attention.
2. As a **Repair officer**, I want to see three shape buttons (Square, Triangle, Circle) so I can attempt a repair.
3. As a **Repair officer**, I want the shape buttons to be disabled when all three repair teams are busy so I cannot waste an attempt.
4. As a **Repair officer**, I want the shape buttons to be disabled when the breakdown queue is empty so I cannot accidentally waste a team.
5. As a **Repair officer**, I want the breakdown row to show "All Systems Nominal" when the queue is empty so I have clear positive feedback.
6. As a **Repair officer**, I want pressing a shape button when the queue is empty to put a team on cooldown, punishing button-mashing.
7. As a **Repair officer**, I want pressing the correct shape to immediately dispatch the lowest-numbered free repair team to the job.
8. As a **Repair officer**, I want the dispatched breakdown to disappear from the queue immediately so the next breakdown is revealed.
9. As a **Repair officer**, I want pressing the wrong shape to put the lowest-numbered free team on a 10-second cooldown.
10. As a **Repair officer**, I want to see three team status rows, each showing a colour-coded progress bar with overlaid status text.
11. As a **Repair officer**, I want idle teams shown in blue with an empty bar so I can see available capacity at a glance.
12. As a **Repair officer**, I want repairing teams shown in green with a filling bar over 30 seconds so I know how long until the job is done.
13. As a **Repair officer**, I want teams on cooldown shown in red with a draining bar over 10 seconds so I know when they will be free.
14. As a **Repair officer**, I want in-progress repairs to never be interrupted by new breakdowns so my team decisions are stable.
15. As a **Repair officer**, I want two teams to be able to repair different breakdowns on the same console simultaneously if that console appears multiple times in the queue.
16. As a **Helm player**, I want a damage icon to appear on my console screen when Helm is broken down so I can call out the shape to the Repair officer.
17. As a **Tactical player**, I want a damage icon to appear on my console screen when Tactical is broken down so I can call out the shape.
18. As a **Science player**, I want a damage icon to appear on my console screen when Science is broken down so I can call out the shape.
19. As **any crew member**, I want a decoy damage icon to sometimes appear on my console even when my console is healthy, creating uncertainty about which breakdowns are real.
20. As **any crew member**, I want the damage icon to disappear from my console as soon as a repair team is dispatched to fix it.
21. As **any crew member**, I want all damage icons to disappear when there are no active breakdowns so the UI is clean during normal operation.
22. As a **crew member on a damaged console**, I want the icon shape to remain fixed for the lifetime of the breakdown so I can reliably call it out.
23. As a **Power officer**, I want to see the current power level (1–4) for each of Helm, Weapons, and Science so I know the current allocation.
24. As a **Power officer**, I want increment and decrement buttons per console so I can adjust power allocation.
25. As a **Power officer**, I want the increment button disabled when the total allocated points reach the cap (6 base + up to 2 from battery) so I cannot over-allocate.
26. As a **Power officer**, I want the decrement button disabled when a console is already at 1 so I cannot cut power below minimum.
27. As a **Power officer**, I want to see the auxiliary battery charge level so I know how much burst power is available.
28. As a **Power officer**, I want all buttons locked during battery exhaustion so I understand why I cannot make changes.
29. As a **Power officer**, I want buttons to unlock once the battery recovers to the emergency threshold so I know when control is restored.
30. As a **Helm player**, I want my max speed and turn rate to be affected by my console's power level so that power decisions have a felt impact.
31. As a **Tactical player**, I want my phaser damage to be affected by Weapons power level so that power allocation matters in combat.
32. As a **Science player**, I want my radar range to be affected by Science power level so that power trade-offs affect exploration.
33. As **any crew member**, I want to see the current power levels for all consoles in the sim state so I understand the ship's current configuration.
34. As a **lobby player**, I want to see Repair and Power as separate selectable consoles so I can choose my role.
35. As a **small crew**, I want one player to be able to hold both Repair and Power consoles so the game is playable with fewer people.

### Console enum

- `Console::Engineering` is renamed to `Console::Repair`.
- A new `Console::Power` variant is added.
- Both appear in the lobby console selection list.
- A single player may hold both if the crew is small.

### Shape enum

- A new `Shape` enum is added to `messages.rs` with variants `Square`, `Triangle`, `Circle`.
- It derives `Clone, Debug, PartialEq, Serialize, Deserialize`.
- `Shape` is used in `BreakdownEntry`, `ClientMessage::Repair`, `ServerMessage::ShowRepairIcon`, and `TeamSlot`.

### BreakdownEntry struct

- `BreakdownQueue` currently stores `VecDeque<Console>`. This is changed to `VecDeque<BreakdownEntry>`.
- `BreakdownEntry { console: Console, shape: Shape }` — shape assigned randomly at push time and fixed for the lifetime of the entry.
- `push_random` assigns both a console (non-repeating) and a random shape.
- `front()` and `pop_front()` return `Option<&BreakdownEntry>` and `Option<BreakdownEntry>` respectively.

### RepairTeams resource

- A new pure-Rust struct `RepairTeams` is introduced, held as a Bevy resource in the simulation plugin.
- It manages exactly 3 team slots.
- `TeamSlot` is an enum: `Idle`, `Repairing { progress: f32 }`, `Cooldown { progress: f32 }`.
- Public interface: `dispatch(team_idx)` marks team as repairing; `penalise(team_idx)` marks team as cooldown; `tick(dt)` advances all timers, returns any teams that completed repair (to apply HP).
- Repair duration: 30 seconds (1 HP per 3 seconds, 10 HP total). Cooldown duration: 10 seconds.
- On a correct shape press: lowest-numbered idle team is dispatched, breakdown is popped from queue.
- On an incorrect shape press: lowest-numbered idle team is penalised.
- In-progress repairs are never interrupted by new queue entries.
- Two teams may repair different entries for the same console simultaneously.

### Decoy icon management

- The server tracks the current decoy console as part of breakdown/repair state.
- On every queue change (push or pop), the server recomputes the full icon state: sends `ClearRepairIcon` to the old decoy (if any), assigns a new random decoy from undamaged consoles, sends `ShowRepairIcon` to the new decoy.
- Real icons: `ShowRepairIcon { shape }` sent to each damaged console's holder on push; `ClearRepairIcon` sent on pop.
- If there are no undamaged consoles, no decoy is shown.
- If the queue becomes empty, all icons are cleared.

### New and modified ServerMessages

- `ServerMessage::ShowRepairIcon { shape: Shape }` — targeted to a specific console holder (real or decoy); client renders icon on their panel.
- `ServerMessage::ClearRepairIcon` — targeted to a specific console holder; client removes icon.
- `ServerMessage::RepairState` — extended to include `teams: [TeamSlot; 3]` and `current_breakdown: Option<(Console, Shape)>` (the head of the queue visible to the Repair officer). `authorized_repair_console` field removed.
- `ServerMessage::PowerState { helm: u8, weapons: u8, science: u8, battery_charge: f32, locked: bool }` — new message broadcast at 10Hz to the Power console holder only.
- `ServerMessage::SimState` — extended to include `power_levels: (u8, u8, u8)` for (Helm, Weapons, Science), visible to all clients.

### New ClientMessages

- `ClientMessage::Repair { shape: Shape }` — replaces the old `Repair { console }`. Sent by the Repair console holder when a shape button is pressed. Server validates: sender holds `Console::Repair`, a free team exists, and checks shape against head of breakdown queue.
- `ClientMessage::IncreasePower { console: Console }` — sent by Power console holder to increment a console's power level by 1.
- `ClientMessage::DecreasePower { console: Console }` — sent by Power console holder to decrement a console's power level by 1.
- Both power messages are ignored by the server if the sender does not hold `Console::Power` or if buttons would be logically disabled.

### Power system resource

- A new pure-Rust struct `PowerSystem` is introduced, held as a Bevy resource.
- Tracks current power levels (helm, weapons, science: each 1–4), battery charge (f32, 0–100), and locked state.
- Public interface: `increase(console)`, `decrease(console)`, `tick(dt)` updates battery charge using the rate table, returns whether locked state changed.
- Base points: 6. Auxiliary battery provides up to 2 extra. Total cap: 8.
- Battery rate table indexed by total allocated points (3–8): `[6.0, 5.0, 4.0, 2.0, -2.0, -6.0]` charge per second.
- Exhaustion: battery hits 0, all consoles forced to 1, locked = true, recharges at max rate. Unlocks when charge reaches `emergency_threshold` (default 25%).
- On any power level change, registers a modifier on `ShipModifiers` via `ModifierSource::Console(console)` for the relevant slots.

### Modifier wiring (depends on PRD #117)

- Helm power maps to `ModifierSlot::MaxSpeed` and `ModifierSlot::MaxYawRate`.
- Weapons power maps to `ModifierSlot::PhaserDamage`.
- Science power maps to `ModifierSlot::RadarRange`.
- Multiplier lookup tables per console (index 0 = level 1, index 3 = level 4):
  - Default bonus values: `[-0.5, 0.0, 0.25, 0.5]` for all slots.
  - Level 2 = baseline (0.0 bonus = 1.0 multiplier). Level 1 = half performance. Level 4 = +50%.
- Tables are configurable in `player_ship.toml` under each console's section (e.g. `[helm.power_multipliers]`).

### EntityConfig changes

- Each console section gains an optional `power_multipliers` table.
- A new `[power]` section is added for battery configuration: `capacity`, `rates`, `emergency_threshold`.

### Repair console UI (client)

- Layout (top to bottom): breakdown row, shape buttons row, Team 1 row, Team 2 row, Team 3 row.
- Breakdown row: shows current console name and shape, or "All Systems Nominal" if queue is empty.
- Shape buttons: Square, Triangle, Circle. Disabled when all teams are busy or queue is empty.
- Team rows: full-width progress bar, status text overlaid. Blue=Idle (empty bar), Green=Repairing (filling over 30s), Red=Cooldown (draining over 10s).

### Power console UI (client)

- Three rows for Helm, Weapons, Science: each shows console name, current level (1–4), decrement and increment buttons.
- Battery charge bar and percentage display.
- All controls locked (greyed) during battery exhaustion.

### authorized_repair_console removal

- `authorized_repair_console` is removed from `SimState` and all related server logic.
- Shape-matching is the sole gating mechanic for repair.

## Testing Decisions

A good test sets up state, performs an action, and asserts on observable output through the public interface. Tests must not assert on private fields, internal call counts, or implementation details.

### breakdown.rs (pure Rust)

- `BreakdownEntry` has both a console and a shape after `push_random`.
- Shape is one of the three valid variants.
- Consecutive pushes never repeat the same console (existing invariant preserved).
- `front()` returns the correct entry after pushes.
- `pop_front()` removes the front entry and exposes the next.
- Prior art: existing `breakdown.rs` inline tests.

### repair_teams.rs (pure Rust, new module)

- New queue starts with all 3 teams idle.
- `lowest_free_team()` returns team 0 when all idle, team 1 when team 0 is busy, None when all busy.
- Dispatching a team moves it to Repairing; progress starts at 0.0.
- Penalising a team moves it to Cooldown; progress starts at 1.0.
- `tick(dt)` advances repairing progress toward 1.0 over 30s.
- `tick(dt)` drains cooldown progress toward 0.0 over 10s; team returns to Idle when complete.
- Repairing team completes after 30s cumulative tick and returns to Idle.
- Two teams can be independently in different states simultaneously.
- Prior art: `ship_physics.rs`, `damage.rs`, `breakdown.rs` pure module tests.

### power_system.rs (pure Rust, new module)

- Default state: helm=2, weapons=2, science=2, battery=100, locked=false.
- `increase(Helm)` increments helm to 3.
- `increase` on a console already at 4 is a no-op.
- `decrease` on a console already at 1 is a no-op.
- Total points cap: `increase` is a no-op when total allocated = 8.
- `tick(dt)` discharges battery when total > 6, recharges when total < 6.
- Battery hits 0: locked=true, all consoles forced to 1.
- Battery recovers to emergency_threshold: locked=false.
- While locked, `increase` and `decrease` are no-ops.
- Prior art: `ship_physics.rs` pure module tests.

### messages.rs codec tests

- Round-trip for `ClientMessage::Repair { shape: Shape::Triangle }`.
- Round-trip for `ClientMessage::IncreasePower { console: Console::Helm }`.
- Round-trip for `ClientMessage::DecreasePower { console: Console::Science }`.
- Round-trip for `ServerMessage::ShowRepairIcon { shape: Shape::Circle }`.
- Round-trip for `ServerMessage::ClearRepairIcon`.
- Round-trip for `ServerMessage::PowerState { .. }`.
- Round-trip for `ServerMessage::ConsoleSelected` with `Console::Repair` and `Console::Power`.
- Prior art: existing codec round-trip tests in `codec.rs`.

### simulation.rs integration tests (Bevy)

- Non-Power-holder sending `IncreasePower` is ignored.
- Power-holder sending `IncreasePower` changes power level and a modifier is registered.
- Correct shape press dispatches a team and pops the breakdown.
- Incorrect shape press puts a team on cooldown, breakdown remains at head.
- All three teams busy: server ignores further shape button presses.
- `RepairState` broadcast includes team slot data.
- `PowerState` broadcast is sent to Power holder only.
- `SimState` broadcast includes power levels.
- `ShowRepairIcon` is sent to a damaged console's holder on breakdown push.
- `ClearRepairIcon` is sent when breakdown is popped.
- Decoy `ShowRepairIcon` is sent to a random undamaged console on breakdown push.
- Old decoy receives `ClearRepairIcon` before new decoy is assigned.
- All icons cleared when queue becomes empty.
- Prior art: existing `simulation.rs` Bevy test helpers (`test_app()`, `push()`, `tick()`).

### client_lobby.rs (pure Rust)

- `Console::Repair` and `Console::Power` appear in `ALL_CONSOLES`.
- `is_repair()` and `is_power()` helper methods on `LobbyView`.
- Prior art: existing `client_lobby.rs` tests.

## Out of Scope

- The Modifier System implementation itself (PRD #117) — this PRD depends on it but does not implement it.
- Science console implementation — Science is a powered console in this PRD but its UI is being built separately.
- Shield regeneration as a power effect — shields are not yet implemented.
- Torpedo damage as a power effect — torpedoes are not yet in scope.
- Acceleration as a power modifier slot — dropped in favour of MaxSpeed and MaxYawRate only.
- Client-side modifier buff/debuff display UI — modifier messages exist on the wire but rendering active modifiers is a separate concern.
- Any renderer or 3D visual changes — damage icons and repair team UI are phone-console UI only.
- The Captain console — no changes to captain authority or UI in this PRD.

## Further Notes

The shape-matching mechanic is intentionally symmetric: `ShowRepairIcon` and `ClearRepairIcon` are identical whether the console is a real target or a decoy. This means clients never know their own role, preserving the social deduction element that drives crew communication.

The three repair teams are a soft resource cap. With 3 teams and 10-second cooldowns, an engineer who misidentifies shapes repeatedly can exhaust all teams simultaneously, creating a brief window of zero repair capacity. This is the intended tension.

The power system's dependency on PRD #117 means power allocation UI can ship first as a no-op (buttons work, battery ticks, but no modifiers are registered until #117 lands). This allows incremental delivery.

The rename of `Console::Engineering` to `Console::Repair` is a breaking wire change — any saved session tokens or in-flight messages using the old string will fail to deserialise. Since the game has no persistent sessions across deploys this is acceptable.

**Comment by jkeywo** [comment]
Broken into vertical slices: #143, #144, #145, #146, #147, #148, #149, #150, #151, #152.
